rango/urls.py
from django.conf.urls import url
from rango import views

app_name = 'rango'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^about/', views.about, name='about'),
    url(r'^add_category/$', views.add_category, name='add_category'),
    url(r'^category/(?P<category_name_slug>[\w\-]+)/add_page/$',
        views.add_page, name='add_page'),
    url(r'^category/(?P<category_name_slug>[\w\-]+)/$',
        views.show_category, name='show_category'),
    url(r'^search/', views.search, name='search'),
    # url(r'^register/$', views.register, name='register'),
    # url(r'^login/$', views.user_login, name="login"),
    url(r'^restricted/$', views.restricted, name="restricted"),
    # url(r'^logout/$', views.user_logout, name='logout'),
    url(r'^goto/', views.track_url, name="goto"),
    url(r'^add_profile/', views.register_profile, name="add_profile"),
    url(r'^profile/(?P<username>[\w\-]+)/$', views.profile, name="profile"),
    url(r'^list_users/', views.list_users, name="list_users"),
    url(r'^profiles/$', views.list_profiles, name="list_profiles"),
    url(r'^like/$', views.like_category, name="like_category"),
    url(r'^suggest/$', views.suggest_category, name="suggest_category"),
    url(r'^add/$', views.auto_add_page, name="auto_add_page"),
]

tango_with_django_project/urls.py
from django.contrib import admin
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.conf import settings
from rango import views
from registration.backends.simple.views import RegistrationView
from django.core.urlresolvers import reverse



class MyRegistrationView(RegistrationView):
    def get_success_url(self, user):
        return reverse('rango:add_profile')


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.index, name='index'),
    # any url pattern starting with 'rango' is directed to the
    # rango urls.py file
    url(r'^rango/', include('rango.urls')),
    url(r'^accounts/register/$', MyRegistrationView.as_view(),
        name='registration_register'),
    url(r'^accounts/', include('registration.backends.simple.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

rango/models.py
from django.db import models
from django.template.defaultfilters import slugify
from django.contrib.auth.models import User
from datetime import datetime


class Category(models.Model):
    name = models.CharField(max_length=128, unique=True)
    views = models.IntegerField(default=0)
    likes = models.IntegerField(default=0)
    slug = models.SlugField(unique=True)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        if(self.views < 0):
            self.views = 0
        super(Category, self).save(*args, **kwargs)

    class Meta:
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.name


class Page(models.Model):
    category = models.ForeignKey(Category)
    title = models.CharField(max_length=128)
    url = models.URLField()
    views = models.IntegerField(default=0)
    first_visit = models.DateTimeField(null=True)
    last_visit = models.DateTimeField(null=True)

    def __str__(self):
        return self.title


class UserProfile(models.Model):
    user = models.OneToOneField(User)
    website = models.URLField(blank=True)
    picture = models.ImageField(upload_to='profile_images', blank=True)

    def __str__(self):
        return self.user.username

rango/forms.py
from django import forms
from django.contrib.auth.models import User
from rango.models import Category, Page, UserProfile
# from django.core.validators import URLValidator


class CategoryForm(forms.ModelForm):
    name = forms.CharField(max_length=128, help_text="Enter Category name")
    views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    likes = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    slug = forms.CharField(widget=forms.HiddenInput(), required=False)

    class Meta:
        model = Category
        fields = ('name', )


class PageForm(forms.ModelForm):
    title = forms.CharField(max_length=128, help_text="Enter Page title")
    url = forms.URLField(max_length=200, help_text="Enter URL of the page")
    views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)

    class Meta:
        model = Page
        exclude = ('category',)

    def clean(self):
        cleaned_data = self.cleaned_data
        url = cleaned_data.get('url')

        if url and not url.startswith('http://'):
            url = 'http://' + url
            cleaned_data['url'] = url
            return cleaned_data


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username', 'email', 'password')


class UserProfileForm(forms.ModelForm):
    website = forms.URLField(required=False)
    picture = forms.ImageField(required=False)

    class Meta:
        model = UserProfile
        # fields = ('website', 'picture')
        exclude = ('user', )

rango/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, redirect
from rango.models import Category, Page, UserProfile
from rango.forms import CategoryForm, PageForm, UserForm, UserProfileForm
from django.contrib.auth import authenticate, login, logout
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required
from datetime import datetime
from rango.google_custom_search import run_query
from django.contrib.auth.models import User

# HELPER FUNCTIONS


def visitor_cookie_handler(request):
    visits = int(get_server_side_cookie(request, 'visits', '1'))

    last_visit_cookie = get_server_side_cookie(
        request, 'last_visit', str(datetime.now()))
    last_visit_time = datetime.strptime(
        last_visit_cookie[:-7], '%Y-%m-%d %H:%M:%S')

    if (datetime.now() - last_visit_time).days > 0:
        visits = visits + 1
        request.session['last_visit'] = str(datetime.now())
    else:
        request.session['last_visit'] = last_visit_cookie

    request.session['visits'] = visits


def get_server_side_cookie(request, cookie, default_val=None):
    val = request.session.get(cookie)
    if not val:
        val = default_val
    return val

# VIEWS


def index(request):
    # Construct a dictionary to pass to the template engine as its context.
    # Note the key boldmessage is the same as {{ boldmessage }} in the template!
    # context_dict = {'boldmessage': "Crunchy, creamy, cookie, candy, cupcake!"}

    # request.session.set_test_cookie()     # set test cookie

    category_list = Category.objects.order_by('-likes')[:5]
    page_list = Page.objects.order_by('-views')[:5]
    context_dict = {'categories': category_list, 'pages': page_list}

    visitor_cookie_handler(request)
    context_dict['visits'] = request.session['visits']

    response = render(request, 'rango/index.html', context_dict)
    return response


def about(request):
    # prints out whether the method is a GET or a POST

    # if (request.session.test_cookie_worked()):    # check test cookie
    # print("TEST COOKIE WORKED!")
    # request.session.delete_test_cookie()

    # print(request.method)
    # prints out the user name, if no one is logged in it prints `AnonymousUser`
    # print(request.user)

    visitor_cookie_handler(request)
    context_dict = {'visits': request.session['visits']}
    response = render(request, 'rango/about.html', context_dict)
    return response


def show_category(request, category_name_slug):
    context_dict = {}
    try:
        category = Category.objects.get(slug=category_name_slug)
        pages = Page.objects.filter(category=category).order_by('-views')
        context_dict['pages'] = pages
        context_dict['category'] = category

    except Category.DoesNotExist:
        context_dict['pages'] = None
        context_dict['category'] = None

    context_dict['query'] = category.name
    result_list = []

    if request.method == 'POST':
        query = request.POST['query'].strip()
        if query:
            result_list = run_query(query)
            context_dict['result_list'] = result_list
            context_dict['query'] = query

    return render(request, 'rango/category.html', context_dict)


@ login_required
def add_category(request):
    form = CategoryForm()

    if request.method == 'POST':
        form = CategoryForm(request.POST)
        if form.is_valid():
            form.save(commit=True)
            return index(request)
        else:
            print(form.errors)
    return render(request, 'rango/add_category.html', {'form': form})


@ login_required
def add_page(request, category_name_slug):
    try:
        category = Category.objects.get(slug=category_name_slug)
    except Category.DoesNotExist:
        category = None

    form = PageForm()
    if request.method == 'POST':
        form = PageForm(request.POST)
        if form.is_valid():
            if category:
                page = form.save(commit=False)
                page.category = category
                page.views = 0
                page.first_visit = datetime.now()
                page.last_visit = datetime.now()
                page.save()
                return show_category(request, category_name_slug)
        else:
            print(form.errors)
    context_dict = {'form': form, 'category': category}
    return render(request, 'rango/add_page.html', context_dict)


def register(request):
    registered = False

    if (request.method == 'POST'):
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileForm(data=request.POST)

        if (user_form.is_valid() and profile_form.is_valid()):
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            if ('picture' in request.FILES):
                profile.picture = request.FILES['picture']

            profile.save()

            registered = True
        else:
            print(user_form.errors, profile_form.errors)
    else:
        user_form = UserForm()
        profile_form = UserProfileForm()

    content_dict = {'user_form': user_form,
                    'profile_form': profile_form,
                    'registered': registered
                    }

    return render(request, 'rango/register.html', content_dict)


def user_login(request):
    if (request.method == 'POST'):
        username = request.POST.get('username')
        password = request.POST.get('password')
        content_dict = {}

        user = authenticate(username=username, password=password)
        if (user):
            if (user.is_active):
                login(request, user)
                return HttpResponseRedirect(reverse('rango:index'))
            else:
                return HttpResponse("Your Rango account is disabled.")
        else:
            print("Invalid login details: {0}, {1}".format(username, password))
            content_dict['incorrect_credentials'] = True
            return render(request, 'rango/login.html', content_dict)
    else:
        return render(request, 'rango/login.html', {})


@ login_required
def restricted(request):
    return render(request, 'rango/restricted.html', {})


@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('rango:index'))


def search(request):
    result_list = []
    query = ""
    if request.method == 'POST':
        query = request.POST['query'].strip()
        if query:
            result_list = run_query(query)

    return render(request, 'rango/search.html', {'result_list': result_list, 'query': query})


def track_url(request):
    page_id = None
    url = '/rango/'
    if request.method == 'GET':
        if 'page_id' in request.GET:
            page_id = request.GET['page_id']
            try:
                page = Page.objects.get(id=page_id)
                page.views += 1
                page.last_visit = datetime.now()
                if(page.first_visit == None):
                    page.first_visit = datetime.now()
                page.save()
                url = page.url
            except:
                pass

    return redirect(url)


@login_required
def register_profile(request):
    if request.method == 'POST':
        profile_form = UserProfileForm(data=request.POST)
        if profile_form.is_valid():
            profile = profile_form.save(commit=False)
            profile.user = request.user

            if ('picture' in request.FILES):
                profile.picture = request.FILES['picture']

            profile.save()
            return HttpResponseRedirect(reverse('rango:index'))
        else:
            print(profile_form.errors)
    else:
        profile_form = UserProfileForm()

    content_dict = {'form': profile_form}

    return render(request, 'rango/profile_registration.html', content_dict)


@login_required
def profile(request, username):
    try:
        user = User.objects.get(username=username)
    except User.DoesNotExist:
        return redirect('rango:index')

    userprofile = UserProfile.objects.get_or_create(user=user)[0]
    form = UserProfileForm(
        {'website': userprofile.website, 'picture': userprofile.picture})

    '''
    if request.method == 'POST':
        username = request.POST.get('username')
        email = request.POST.get('email')
        website = request.POST.get('website')
        picture = request.FILES['picture']

        user.username = username
        user.email = email
        userprofile.website = website
        userprofile.picture = picture

        user.save()
        userprofile.save()

        return HttpResponseRedirect(reverse('rango:index'))

    content_dict = {'user': user, 'user_profile': user_profile}
    return render(request, 'rango/profile.html', content_dict)      '''

    if request.method == 'POST':
        form = UserProfileForm(
            request.POST, request.FILES, instance=userprofile)
        if form.is_valid():
            form.save(commit=True)
            return redirect('rango:profile', user.username)
        else:
            print(form.errors)
    context_dict = {'userprofile': userprofile,
                    'selecteduser': user, 'form': form}
    return render(request, 'rango/profile.html', context_dict)


def list_users(request):
    user_profile_list = UserProfile.objects.all()
    users_list = []

    for user_profile in user_profile_list:
        user = user_profile.user
        website = user_profile.website
        user_info = {"username": user.username,
                     "email": user.email,
                     "website": website}
        users_list.append(user_info)

    content_dict = {'users_list': users_list}
    return render(request, 'rango/list_users_old.html', content_dict)


@login_required
def list_profiles(request):
    userprofile_list = UserProfile.objects.all()

templates/rango/base.html
<!DOCTYPE html>
{% load staticfiles %}
{% load rango_template_tags %}


<html lang="en">
<head>
   <meta charset="utf-8">
   <meta http-equiv="X-UA-Compatible" content="IE=edge">
   <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
   <meta name="description" content="">
   <meta name="author" content="">
   <link rel="icon" href="{% static 'images/favicon.ico' %}">

   <title>
      Rango - {% block title_block %} How to Tango with Django {% endblock %}
   </title>

   <!-- <link href="http://v4-alpha.getbootstrap.com/dist/css/bootstrap.min.css" rel="stylesheet"> -->
   <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">

   <!-- <link href="http://v4-alpha.getbootstrap.com/examples/dashboard/dashboard.css" rel="stylesheet"> -->
   <link rel="stylesheet" href="{% static 'css/dashboard.css' %}">

   <style>
      .btn-circle {
         border-radius: 25px;
      }
   </style>

</head>

<body>
   <nav class="navbar navbar-toggleable-md navbar-inverse fixed-top bg-inverse">
      <button  class="navbar-toggler navbar-toggler-right hidden-lg-up"
               type="button" 
               data-toggle="collapse"
               data-target="#navbar"
               aria-controls="navbar"
               aria-expanded="false"
               aria-lable="Toggle navigation">
         <span class="navbar-toggler-icon"></span>
      </button>
      <a class="navbar-brand" href="{% url 'rango:index' %}">Rango</a>

      <div class="collapse navbar-collapse" id="navbar">
         <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
               <a class="nav-link" href="{% url 'rango:index' %}"> Home </a>  
            </li>
            <li class="nav-item">
               <a class="nav-link" href="{% url 'rango:about' %}"> About </a>
            </li>
            <!-- <li class="nav-item">
               <a class="nav-link" href="{% url 'rango:search' %}"> Search </a>
            </li> -->
            
            {% if user.is_authenticated %}
               <li class="nav-item">
                  <a class="nav-link" href="{% url 'rango:restricted' %}"> Restricted Page </a>
               </li>
               <li class="nav-item">
                  <a class="nav-link" href="{% url 'rango:profile' user.username %}"> Profile </a>
               </li>
               <li class="nav-item">
                  <a class="nav-link" href="{% url 'rango:list_profiles' %}"> List Profiles </a>
               </li>
               <!--
               <li class="nav-item">
                  <a class="nav-link" href="{% url 'rango:list_users' %}"> Rango Users </a>
               </li> -->
               <li class="nav-item">
                  <a class="nav-link" href="{% url 'rango:add_category' %}"> Add a New Category </a>
               </li>
               <li class="nav-item">
                  <a class="nav-link" href="{% url 'auth_logout' %}?next=/rango/"> Logout </a>
               </li>
            {% else %}
               <li class="nav-item">
                  <a class="nav-link" href="{% url 'registration_register' %}">Register Here</a>
               </li>
               <li class="nav-item">
                  <a class="nav-link" href="{% url 'auth_login' %}"> Login </a>
               </li>
            {% endif %}
         </ul>
      </div>
   </nav>

   <div class="container-fluid">
      <div class="row">
         <div class="col-sm-3 col-md-2 sidebar">
            <ul class="nav nav-list flex-column">
               <li class="nav-item"> Type to find a category </li>
               <form>
                  <li class="nav-item">
                     <input class="search-query form-control" type="text" name="suggestion" id="suggestion" value="" />
                  </li>
               </form>
            </ul>
            <hr />
            
            <div id="cats">
               {% block sidebar_block %}
                  {% get_category_list category %}
               {% endblock %}
            </div>

            
            

         </div>

         <div class="col-sm-9 offset-sm-3 col-md-10 offset-md-2 main">
            <br /> 
            {% block body_block %}

            {% endblock %}
         </div>
      </div>
   </div>

   <!-- <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"> </script> -->
   <!-- <script src="{% static 'jquery/jquery.min_old.js' %}"></script> -->

   <!-- <script src="http://v4-alpha.getbootstrap.com/dist/js/bootstrap.min.js"> </script> -->
   <script src="{% static 'js/bootstrap.min.js' %}"></script>

   <!-- <script src="http://v4-alpha.getbootstrap.com/assets/js/ie10-viewport-bug-workaround.js"> </script> -->
   <script src="{% static 'js/ie10-viewport-bug-workaround.js' %}"></script>

   <!-- <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.0.0/jquery.min.js"> -->
   <script src="{% static 'jquery/jquery.min.js' %}"></script>
   <script src="{% static 'jquery/rango-jquery.js' %}"></script>
   <script src="{% static 'jquery/rango-ajax.js' %}"></script>

</body>

</html>

templates/rango/base_old.html
<!DOCTYPE html>
{% load staticfiles %}
{% load rango_template_tags %}

<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>
            Rango -
            {% block title_block %}
                How to Tango with Django
            {% endblock %}
        </title>
    </head>
    <body>
        <div>
            {% block body_block %}
            {% endblock %}
        </div>
        <div>
            {% block sidebar_block %}
                {% get_category_list category %}
            {% endblock %}
        </div>
        <hr />
        <div>
            <ul>
                {% if user.is_authenticated %}
                    <li> <a href="{% url 'rango:restricted' %}"> Restricted Page </a> </li>
                    <li> <a href="{% url 'auth_logout' %}?next=/rango/"> Logout </a> </li>
                    <li> <a href="{% url 'auth_password_change' %}"> Change Password </a> </li>
                {% else %}
                    <li> <a href="{% url 'auth_login' %}"> Login </a> </li>
                    <li> <a href="{% url 'registration_register' %}"> Sign Up </a> </li>
                {% endif %}
                <li> <a href="{% url 'rango:add_category' %}"> Add New Category </a> </li>
                <li> <a href="{% url 'rango:about' %}" > About </a> </li>
                <li> <a href="{% url 'rango:index' %}"> Home </a></li>
            </ul>
        </div>

    </body>
</html>

templates/rango/category.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
    {{ category.name }}
{% endblock %}

{% block body_block %}
    {% if category %}
            <h1>{{ category.name }}</h1>
            <div>
                <strong id="like_count"> {{ category.likes }} </strong> people like this category
                {% if user.is_authenticated %}
                    <button id="likes" data-catid="{{ category.id }}"
                    class="btn btn-primary btn-sm" type="button">
                        Like
                    </button>
                {% endif %}
            </div>
            <br>
            <div id="pages">
                {% if pages %}
                    <ul>
                        {% for page in pages %}
                            <li>
                                <a href="{% url 'rango:goto' %}?page_id={{ page.id }}"> {{ page.title }} </a>
                                <!--{% if page.views > 1 %} ({{ page.views }} views)
                                {% elif page.views == 1 %} ({{ page.views }} view)
                                {% endif %}-->
                                <button class="btn btn-primary btn-sm btn-circle">{{ page.views }}</button>
                            </li>
                        {% endfor %}
                    </ul>
                {% else %}
                    <strong>No pages currently in category.</strong>
                {% endif %}
            </div>
            {% if user.is_authenticated %}    
                <a href="{% url 'rango:add_page' category.slug %}">Add a Page</a> <br />
            {% endif %}
        {% else %}
            The specified category doesn't exist!
        {% endif %}
        <br />
        {% if user.is_authenticated %}
            <div>
                <h4> Search with Rango </h4>
                <!-- <br /> -->
                <form class="form-inline" id="user_form" method="post" action="{% url 'rango:show_category' category.slug %}">
                    {% csrf_token %}
                    <div class="form-group">
                        <input type="form-control" type="text" size="50" name="query" value="{{ query }}" id="query" />
                    </div>
                    <button class="btn btn-primary" type="submit" name="submit" value="Search"> Search </button>
                </form>

                <div>
                    {% if result_list %}
                        <br >
                        <h3> Results </h3>
                        <div class="list-group">
                            {% for result in result_list %}
                                <div class="list-group-item">
                                    <h4 class="list-group-heading">
                                        <a href="{{ result.link }}"> {{ result.title }} </a> 
                                    </h4>
                                    <p class="list-group-item-text"> {{ result.summary }} </p>
                                    {% if user.is_authenticated %}
                                        <button data-catid="{{category.id}}" data-title="{{result.title}}" data-url="{{result.link}}"
                                                class="rango-add btn btn-info btn-sm" type="button">
                                                Add
                                        </button>
                                    {% endif %}
                                </div>
                            {% endfor %}    
                        </div>
                    {% endif %}
                </div>
            </div>
        {% endif %}
   
{% endblock %}

templates/rango/cats.html
<!DOCTYPE html>
<ul>
  {% if cats %} 
    {% for c in cats %}
      {% if c == act_cat %}
        <li>
        <strong>
          <a href="{% url 'rango:show_category' c.slug %}">{{ c.name }}</a>
        </strong>
        </li>
      {% else %}
        <li>
          <a href="{% url 'rango:show_category' c.slug %}">{{ c.name }}</a>
        </li>
      {% endif %}
    {% endfor %}
  {% else %}
    <li><strong>There are no categories present</strong></li>
  {% endif %}
</ul>

templates/rango/index_old.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block body_block %}
    <h1>Rango says ... </h1>
    <div>
        {% if user.is_authenticated %}
            howdy {{ user.username }}
        {% else %}
            hey there partner!
        {% endif %}
    </div>

    <div>
        <h2>Most Liked Categories</h2>
        {% if categories %}
            <ul>
                {% for category in categories %}
                    <li>
                        <a href="{% url 'rango:show_category' category.slug %}">{{ category.name }}</a>
                    </li>
                {% endfor %}
            </ul>
            {% else %}
                <strong>There are no categories present</strong>
        {% endif %}
    </div>

    <div>
        <h2>Most Viewed Pages</h2>
        {% if pages %}
            <ul>
                {% for page in pages %}
                    <li>
                        <a href="{{ page.url }}" >{{ page.title }}</a>
                    </li>
                {% endfor %}
            </ul>
        {% endif %}
    </div>
    <img src="{% static 'images/rango.jpg' %}" alt="Picture of Rango" />
{% endblock %}

templates/rango/profile_old.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
   Profile
{% endblock %}

{% block body_block %}
   <h1 class="form-signin-heading"> {{ selecteduser.username }} Profile </h1>
   <img src="{{ MEDIA_URL }}{{ userprofile.picture }}" 
        width="300" height="300"
        alt="{{ selecteduser.username }} Picture">
   <br />

   <div>
      {% if selecteduser.username == user.username %}
      <!-- 
         <form role="form" id="profile_form" method="post" action="{% url 'rango:profile' %}" enctype="multipart/form-data" >
            
            {% csrf_token %}
            <div class="form-group">
               <p class="required">
                  <label class="required" for="id_username"> Username: </label>
                  <input class="form-control" id="id_username" maxlength="30" name="username" type="text" value="{{ user.username }}" />
               </p>

               <p class="required">
                  <label class="required" for="id_email"> Email: </label>
                  <input class="form-control" id="id_email" maxlength="254" name="email" type="email" value="{{ user.email }}" />
               </p>

               <p class="required">
                  <label class="required" for="id_website"> Website: </label>
                  <input class="form-control" id="id_website" maxlength="200" name="website" type="url" value="{{ user_profile.website }}" />
               </p>

               <p class="required">
                  <label class="required" for="id_picture"> Picture: </label>
                  <input class="form-control" id="id_picture" name="picture" type="file" />       
               </p>
            </div>

            <br />
            <button class="btn btn-primary" type="submit" name="submit"> Update </button> 
         </form> -->

         <form method="post" action="." enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Update" />
         </form>

      {% else %}
         <p> <strong> Website: </strong> <a href="{{ userprofile.website }}"> {{ userprofile.website }} </a> 
         </p>
      {% endif %}
   </div>
   <div id="edit_profile"></div>

{% endblock %}

templates/rango/profile_registration.html
{% extends 'rango/base.html' %}

{% block title_block %}
   Add Profile
{% endblock %}

{% block body_block %}
   <form role="form" method="post" action="{% url 'rango:add_profile' %} " enctype="multipart/form-data">
      <h2 class="form-signin-heading"> Add Profiles </h2>
      {% csrf_token %}
      
      <p class="required">
         <label class="required" for="id_website"> Website: </label>
         <input class="form-control" id="id_website" maxlength="200" name="website" type="url" />
      </p>
      
      <p class="required">
         <label class="required" for="id_picture"> Picture: </label>
         <input class="form-control" id="id_picture" name="picture" type="file" />
      </p>

      <br />
      <button class="btn btn-primary" type="submit" name="submit"> Save Profile </button>
   </form>
{% endblock %}

templates/rango/restricted.html
{% extends 'rango/base.html' %}

{% block title_block %}
   Restricted
{% endblock %}

{% block body_block %}
   <h1>Restricted Page!</h1>

    Since you're logged in, you can see this text!
{% endblock %}

templates/rango/search_old.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
   Search
{% endblock %}

{% block body_block %}
   <div>
      <h1> Search with Rango </h1>
      <br />
      <form class="form-inline" id="user_form" method="post" action="{% url 'rango:search' %}">
         {% csrf_token %}
         <div class="form-group">
            <input type="form-control" type="text" size="50" name="query" value="{{ query }}" id="query" />
         </div>
         <button class="btn btn-primary" type="submit" name="submit" value="Search"> Search </button>
      </form>

      <div>
         {% if result_list %}
         <br >
            <h3> Results </h3>
            <div class="list-group">
               {% for result in result_list %}
                  <div class="list-group-item">
                     <h4 class="list-group-heading">
                        <a href="{{ result.link }}"> {{ result.title }} </a> 
                      </h4>
                      <p class="list-group-item-text"> {{ result.summary }} </p>
                  </div>
               {% endfor %}
            </div>
         {% endif %}
      </div>
   </div>
{% endblock %}